apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ts-videos
commonLabels:
  app: tsVideosManager

resources:
- deployment-frontend.yaml
- deployment-backend.yaml
- service-frontend.yaml
- service-backend.yaml
- config-map.yaml
- sealed-secret.yaml
