kind: Service
apiVersion: v1
metadata:
  name: ts-videos-manager-service-backend
  annotations:
    metallb.io/allow-shared-ip: ts-videos-manager
    metallb.io/loadBalancerIPs: 192.168.2.54
spec:
  selector:
    deployment: ts-videos-manager-deployment-backend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
