kind: Service
apiVersion: v1
metadata:
  name: ts-videos-manager-service-frontend
  annotations:
    metallb.io/allow-shared-ip: ts-videos-manager
    metallb.io/loadBalancerIPs: 192.168.2.54
spec:
  selector:
    deployment: ts-videos-manager-deployment-frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
