apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stash
commonLabels:
  app: stash

resources:
- namespace.yaml
- persistent-volume.yaml
- persistent-volume-claim.yaml
- deployment.yaml
- service.yaml
- sealed-secret.yaml
