apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-media-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: stash-media-pv
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: stash-data-pv
  resources:
    requests:
      storage: 100Gi
